package tesAct.model;

import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from .VCARD.owl
 * 
 * @author Auto-generated by schemagen on 15 jun 2014 15:14
 */
public class VCARD {
	/**
	 * <p>
	 * The ontology model that holds the vocabulary terms
	 * </p>
	 */
	private static OntModel m_model = ModelFactory.createOntologyModel(
			OntModelSpec.OWL_MEM, null);

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "http://www.w3.org/2002/07/owl#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = m_model.createResource(NS);

	public static final ObjectProperty adr = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#adr");

	public static final ObjectProperty agent = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#agent");

	public static final ObjectProperty email = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#email");

	public static final ObjectProperty geo = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#geo");

	public static final ObjectProperty hasAdditionalName = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasAdditionalName");

	public static final ObjectProperty hasAddress = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasAddress");

	public static final ObjectProperty hasCalendarBusy = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasCalendarBusy");

	public static final ObjectProperty hasCalendarLink = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasCalendarLink");

	public static final ObjectProperty hasCalendarRequest = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasCalendarRequest");

	public static final ObjectProperty hasCategory = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasCategory");

	public static final ObjectProperty hasCountryName = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasCountryName");

	public static final ObjectProperty hasEmail = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasEmail");

	public static final ObjectProperty hasFN = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasFN");

	public static final ObjectProperty hasFamilyName = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasFamilyName");

	public static final ObjectProperty hasGender = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasGender");

	public static final ObjectProperty hasGeo = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasGeo");

	public static final ObjectProperty hasGivenName = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasGivenName");

	public static final ObjectProperty hasHonorificPrefix = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasHonorificPrefix");

	public static final ObjectProperty hasHonorificSuffix = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasHonorificSuffix");

	public static final ObjectProperty hasInstantMessaging = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasInstantMessaging");

	public static final ObjectProperty hasKey = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasKey");

	public static final ObjectProperty hasLanguage = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasLanguage");

	public static final ObjectProperty hasLocality = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasLocality");

	public static final ObjectProperty hasLogo = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasLogo");

	public static final ObjectProperty hasMember = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasMember");

	public static final ObjectProperty hasName = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasName");

	public static final ObjectProperty hasNickname = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasNickname");

	public static final ObjectProperty hasNote = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasNote");

	public static final ObjectProperty hasOrganizationName = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasOrganizationName");

	public static final ObjectProperty hasOrganizationUnit = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasOrganizationUnit");

	public static final ObjectProperty hasPhoto = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasPhoto");

	public static final ObjectProperty hasPostalCode = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasPostalCode");

	public static final ObjectProperty hasRegion = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasRegion");

	public static final ObjectProperty hasRelated = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasRelated");

	public static final ObjectProperty hasRole = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasRole");

	public static final ObjectProperty hasSound = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasSound");

	public static final ObjectProperty hasSource = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasSource");

	public static final ObjectProperty hasStreetAddress = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasStreetAddress");

	public static final ObjectProperty hasTelephone = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasTelephone");

	public static final ObjectProperty hasTitle = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasTitle");

	public static final ObjectProperty hasUID = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasUID");

	public static final ObjectProperty hasURL = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasURL");

	public static final ObjectProperty hasValue = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#hasValue");

	public static final ObjectProperty key = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#key");

	public static final ObjectProperty logo = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#logo");

	public static final ObjectProperty name = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#name");

	public static final ObjectProperty organization = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#organization");

	public static final ObjectProperty photo = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#photo");

	public static final ObjectProperty sound = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#sound");

	public static final ObjectProperty telephone = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#telephone");

	public static final ObjectProperty url = m_model
			.createObjectProperty("http://www.w3.org/2006/vcard/ns#url");

	public static final DatatypeProperty additional_name = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#additional-name");

	public static final DatatypeProperty anniversary = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#anniversary");

	public static final DatatypeProperty bday = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#bday");

	public static final DatatypeProperty category = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#category");

	public static final DatatypeProperty class_ = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#class");

	public static final DatatypeProperty country_name = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#country-name");

	public static final DatatypeProperty extended_address = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#extended-address");

	public static final DatatypeProperty family_name = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#family-name");

	public static final DatatypeProperty fn = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#fn");

	public static final DatatypeProperty given_name = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#given-name");

	public static final DatatypeProperty honorific_prefix = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#honorific-prefix");

	public static final DatatypeProperty honorific_suffix = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#honorific-suffix");

	public static final DatatypeProperty label = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#label");

	public static final DatatypeProperty language = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#language");

	public static final DatatypeProperty latitude = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#latitude");

	public static final DatatypeProperty locality = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#locality");

	public static final DatatypeProperty longitude = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#longitude");

	public static final DatatypeProperty mailer = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#mailer");

	public static final DatatypeProperty nickname = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#nickname");

	public static final DatatypeProperty note = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#note");

	public static final DatatypeProperty organization_name = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#organization-name");

	public static final DatatypeProperty organization_unit = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#organization-unit");

	public static final DatatypeProperty post_office_box = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#post-office-box");

	public static final DatatypeProperty postal_code = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#postal-code");

	public static final DatatypeProperty prodid = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#prodid");

	public static final DatatypeProperty region = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#region");

	public static final DatatypeProperty rev = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#rev");

	public static final DatatypeProperty role = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#role");

	public static final DatatypeProperty sort_string = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#sort-string");

	public static final DatatypeProperty street_address = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#street-address");

	public static final DatatypeProperty title = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#title");

	public static final DatatypeProperty tz = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#tz");

	public static final DatatypeProperty value = m_model
			.createDatatypeProperty("http://www.w3.org/2006/vcard/ns#value");

	public static final OntClass Acquaintance = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Acquaintance");

	public static final OntClass Address = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Address");

	public static final OntClass Agent = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Agent");

	public static final OntClass BBS = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#BBS");

	public static final OntClass Car = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Car");

	public static final OntClass Cell = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Cell");

	public static final OntClass Child = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Child");

	public static final OntClass Colleague = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Colleague");

	public static final OntClass Contact = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Contact");

	public static final OntClass Coresident = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Coresident");

	public static final OntClass Coworker = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Coworker");

	public static final OntClass Crush = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Crush");

	public static final OntClass Date = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Date");

	public static final OntClass Dom = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Dom");

	public static final OntClass Email = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Email");

	public static final OntClass Emergency = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Emergency");

	public static final OntClass Fax = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Fax");

	public static final OntClass Female = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Female");

	public static final OntClass Friend = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Friend");

	public static final OntClass Gender = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Gender");

	public static final OntClass Group = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Group");

	public static final OntClass Home = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Home");

	public static final OntClass ISDN = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#ISDN");

	public static final OntClass Individual = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Individual");

	public static final OntClass Internet = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Internet");

	public static final OntClass Intl = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Intl");

	public static final OntClass Kin = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Kin");

	public static final OntClass Kind = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Kind");

	public static final OntClass Label = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Label");

	public static final OntClass Location = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Location");

	public static final OntClass Male = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Male");

	public static final OntClass Me = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Me");

	public static final OntClass Met = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Met");

	public static final OntClass Modem = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Modem");

	public static final OntClass Msg = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Msg");

	public static final OntClass Muse = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Muse");

	public static final OntClass Name = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Name");

	public static final OntClass Neighbor = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Neighbor");

	public static final OntClass None = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#None");

	public static final OntClass Organization = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Organization");

	public static final OntClass Other = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Other");

	public static final OntClass PCS = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#PCS");

	public static final OntClass Pager = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Pager");

	public static final OntClass Parcel = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Parcel");

	public static final OntClass Parent = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Parent");

	public static final OntClass Postal = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Postal");

	public static final OntClass Pref = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Pref");

	public static final OntClass RelationType = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#RelationType");

	public static final OntClass Sibling = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Sibling");

	public static final OntClass Spouse = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Spouse");

	public static final OntClass Sweetheart = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Sweetheart");

	public static final OntClass Tel = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Tel");

	public static final OntClass TelephoneType = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#TelephoneType");

	public static final OntClass Text = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Text");

	public static final OntClass TextPhone = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#TextPhone");

	public static final OntClass Type = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Type");

	public static final OntClass Unknown = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Unknown");

	public static final OntClass VCard = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#VCard");

	public static final OntClass Video = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Video");

	public static final OntClass Voice = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Voice");

	public static final OntClass Work = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#Work");

	public static final OntClass X400 = m_model
			.createClass("http://www.w3.org/2006/vcard/ns#X400");

}
